

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level: 
    root: trace
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,transactions"
  tracing:
    sampling:
      probability: 1.0